version: '3.4'

services:
  client:
    image: client
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules
